repository: HuiSe.cf/HuiSe.cf
repository_url: http://HuiSe.cf

timezone: Asia/Shanghai
lang: zh_CN

title: 灰色导航 · HuiSe.Cf 
alias_en: HuiSe.Cf
alias_cn: 灰色导航
description: A Navigation Website for HuiSe
keywords: 灰色导航, HuiSe, HuiSe, 想要的, Navi, Navigation
url: http://HuiSe.Cf
established_at: "2017-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://www.baidu.com
organization: TEELAB
organization_url: https://www.baidu.com
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
